version: "3.7"

services:
  db:
    image: postgres:12
    container_name: socket_io

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ali20031001a
      POSTGRES_DB: dbusers
    volumes:
      - ./data:/var/lib/postgresql/data

    ports:
      - "5432:5432"