spring:
    application:
        name: Socket_Io
    datasource:
        url: jdbc:postgresql://localhost:5432/dbusers
        username: postgres
        password: Ali20031001a
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect